# Auto-generated by Makefile from .env — do not edit directly.
# Edit ansible/inventory/hosts.yaml.tpl instead.

all:
  hosts:
    awslab:
      ansible_host: ${TARGET_HOST}
      ansible_user: ${TARGET_USER}
      ansible_ssh_private_key_file: ${SSH_KEY_PATH}
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ConnectTimeout=10"
      ansible_python_interpreter: /usr/bin/python3
