---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: emojivoto
  labels:
    app: voting-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
  template:
    metadata:
      labels:
        app: voting-svc
    spec:
      containers:
        - name: voting-svc
          image: docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8801
              name: prom
          env:
            - name: GRPC_PORT
              value: "8080"
            - name: PROM_PORT
              value: "8801"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: emojivoto
spec:
  selector:
    app: voting-svc
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: prom
      port: 8801
      targetPort: 8801
