---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: act-runner-token
  namespace: gitea-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: act-runner-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: act-runner
        property: token
