---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-objstore-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: thanos-objstore-secret
    creationPolicy: Owner
    template:
      data:
        objstore.yml: |
          type: S3
          config:
            bucket: thanos
            endpoint: minio.monitoring.svc.cluster.local:9000
            access_key: "{{ .access_key }}"
            secret_key: "{{ .secret_key }}"
            insecure: true
  data:
    - secretKey: access_key
      remoteRef:
        key: minio
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: minio
        property: secret_key
